### ISSUE TITLE
How does nested configuration work?

### ISSUE THREAD

**Issue by kant111** [fabriziocucci/yacl4j#9]
I have the following in my `yaml` file

```
helium:
  kafkaTopic: hellotopic
  kafkaConsumer:
    bootstrap.servers: localhost:9092
    group.id: indexer29
    enable.auto.commit: false
    auto.commit.interval.ms: 1000
    session.timeout.ms: 30000
    auto.offset.reset: earliest
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
```
How does the Java interface look like? Especially when I cannot have a dot in method names for example  `bootstrap.servers`. I actually don't want to create any methods for properties that are nested under `kafkaConsumer` instead I want to grab all properties under KafkaConsumer as a Map or `java.util.Properties` object

Can I do the following ?

```
import java.util.Properties;

public interface Helium {
    String kafkaTopic();
    Properties kafkaConsumer();
}

```

Here is how I am trying to access it

```
public class TestConfig {

    public static void main(String... args) {
        Helium config = ConfigurationBuilder.newBuilder()
                .source().fromFileOnPath("/Users/hello/application.yaml")
                .build(Helium.class);
        System.out.println(config.kafkaTopic());
    }
}
```

I get the following error

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unimplemented method 'kafkaTopic' (not a setter/getter, could not materialize)

```
